### ISSUE TITLE
баг: Не получается какать, а как

### ISSUE THREAD

**Issue by simple-russia** [bankai671/microserv-playground#1]
1. Не получается какать
При компиляции проекта не получилось какать. Как правильно нужно? А как какать

2. Воспроизведение бага
Скомпилировать сервер на го, сказать: го какать. Какать не получается. А как какать? Воспроизводиств в 95% случаев в 5% не добегаешь

3. Информация о системе и логи ошибки
Туалет: акриловый
Какать: default какать

**Comment by bankai671** [comment]
ладно
